package io.topiacoin.eosrpcadapter;

import io.topiacoin.eosrpcadapter.messages.AccountInfo;
import io.topiacoin.eosrpcadapter.messages.BlockInfo;
import io.topiacoin.eosrpcadapter.messages.ChainInfo;
import io.topiacoin.eosrpcadapter.messages.Code;
import io.topiacoin.eosrpcadapter.messages.TableRows;
import io.topiacoin.eosrpcadapter.messages.Transaction;
import io.topiacoin.eosrpcadapter.messages.TransactionBinArgs;
import io.topiacoin.eosrpcadapter.messages.TransactionJSONArgs;
import org.junit.Test;

import java.io.ByteArrayInputStream;
import java.util.HashMap;
import java.util.Map;

import static junit.framework.TestCase.*;

public abstract class AbstractChainTests {

    protected abstract Chain getChain() ;

    protected abstract Chain getChain(String hostname) ;

    @Test
    public void testChainGetInfo() throws Exception {
        Chain chain = getChain();

        ChainInfo response = chain.getInfo();

        assertNotNull(response);
    }

    @Test
    public void testChainGetBlock() throws Exception {
        Chain chain = getChain();

        BlockInfo response = chain.getBlock("154594");

        assertNotNull(response);
    }

    @Test
    public void testChainGetAccount() throws Exception {
        Chain chain = getChain();

        AccountInfo response = chain.getAccount("inita");

        assertNotNull(response);
    }

    @Test
    public void testChainGetCode() throws Exception {
        Chain chain = getChain();

        Code response = chain.getCode("inita");

        assertNotNull(response);
    }


    @Test
    public void testChainGetTableRows() throws Exception {
        Chain chain = getChain();

        TableRows response = chain.getTableRows("sampledb", "sampledb", "workspace", -1, true);

        assertNotNull(response);
    }

    @Test
    public void testChainAbiJsonToBin() throws Exception {
        Chain chain = getChain("constantine.secrata.com");

        Map<String,String> args = new HashMap<String,String>();
        args.put("from", "inita");
        args.put("type", "foo");
        args.put("data", "bar");

        TransactionBinArgs response = chain.abiJsonToBin("inita", "anyaction", args);

        assertNotNull(response);
    }

    @Test
    public void testChainAbiBinToJson() throws Exception {
        Chain chain = getChain();

        TransactionJSONArgs response = chain.abiBinToJson("inita", "anyaction", "000000000093dd7403666f6f03626172");

        assertNotNull(response);

        System.out.println("Args: " + response.args);
    }

    @Test
    public void testSetContract() throws Exception {
        Chain chain = getChain("constantine.secrata.com");
        String abi = "{\n"
                + "    \"____comment\": \"This file was generated with eosio-abigen. DO NOT EDIT Tue Oct 30 15:49:29 2018\",\n"
                + "    \"version\": \"eosio::abi/1.0\",\n"
                + "    \"structs\": [\n"
                + "        {\n"
                + "            \"name\": \"accept\",\n"
                + "            \"base\": \"\",\n"
                + "            \"fields\": [\n"
                + "                {\n"
                + "                    \"name\": \"invitee\",\n"
                + "                    \"type\": \"name\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"guid\",\n"
                + "                    \"type\": \"uint64\"\n"
                + "                }\n"
                + "            ]\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"acceptowner\",\n"
                + "            \"base\": \"\",\n"
                + "            \"fields\": [\n"
                + "                {\n"
                + "                    \"name\": \"guid\",\n"
                + "                    \"type\": \"uint64\"\n"
                + "                }\n"
                + "            ]\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"ackfile\",\n"
                + "            \"base\": \"\",\n"
                + "            \"fields\": [\n"
                + "                {\n"
                + "                    \"name\": \"user\",\n"
                + "                    \"type\": \"name\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"guid\",\n"
                + "                    \"type\": \"uint64\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"fileID\",\n"
                + "                    \"type\": \"uint128\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"versionID\",\n"
                + "                    \"type\": \"uint128\"\n"
                + "                }\n"
                + "            ]\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"ackmessage\",\n"
                + "            \"base\": \"\",\n"
                + "            \"fields\": [\n"
                + "                {\n"
                + "                    \"name\": \"user\",\n"
                + "                    \"type\": \"name\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"guid\",\n"
                + "                    \"type\": \"uint64\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"msgID\",\n"
                + "                    \"type\": \"uint128\"\n"
                + "                }\n"
                + "            ]\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"addfile\",\n"
                + "            \"base\": \"\",\n"
                + "            \"fields\": [\n"
                + "                {\n"
                + "                    \"name\": \"uploader\",\n"
                + "                    \"type\": \"name\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"guid\",\n"
                + "                    \"type\": \"uint64\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"parentID\",\n"
                + "                    \"type\": \"uint128\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"fileID\",\n"
                + "                    \"type\": \"uint128\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"versionID\",\n"
                + "                    \"type\": \"uint128\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"ancestorVersionIDs\",\n"
                + "                    \"type\": \"uint128[]\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"fileMetadata\",\n"
                + "                    \"type\": \"string\"\n"
                + "                }\n"
                + "            ]\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"addmessage\",\n"
                + "            \"base\": \"\",\n"
                + "            \"fields\": [\n"
                + "                {\n"
                + "                    \"name\": \"author\",\n"
                + "                    \"type\": \"name\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"guid\",\n"
                + "                    \"type\": \"uint64\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"message\",\n"
                + "                    \"type\": \"string\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"mimeType\",\n"
                + "                    \"type\": \"string\"\n"
                + "                }\n"
                + "            ]\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"addperm\",\n"
                + "            \"base\": \"\",\n"
                + "            \"fields\": [\n"
                + "                {\n"
                + "                    \"name\": \"user\",\n"
                + "                    \"type\": \"name\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"target\",\n"
                + "                    \"type\": \"name\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"guid\",\n"
                + "                    \"type\": \"uint64\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"permName\",\n"
                + "                    \"type\": \"string\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"scope\",\n"
                + "                    \"type\": \"string\"\n"
                + "                }\n"
                + "            ]\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"addperms\",\n"
                + "            \"base\": \"\",\n"
                + "            \"fields\": [\n"
                + "                {\n"
                + "                    \"name\": \"user\",\n"
                + "                    \"type\": \"name\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"target\",\n"
                + "                    \"type\": \"name\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"guid\",\n"
                + "                    \"type\": \"uint64\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"permissions\",\n"
                + "                    \"type\": \"userPermission[]\"\n"
                + "                }\n"
                + "            ]\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"addtag\",\n"
                + "            \"base\": \"\",\n"
                + "            \"fields\": [\n"
                + "                {\n"
                + "                    \"name\": \"user\",\n"
                + "                    \"type\": \"name\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"guid\",\n"
                + "                    \"type\": \"uint64\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"fileID\",\n"
                + "                    \"type\": \"uint128\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"versionID\",\n"
                + "                    \"type\": \"uint128\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"isPublic\",\n"
                + "                    \"type\": \"boolean\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"value\",\n"
                + "                    \"type\": \"string\"\n"
                + "                }\n"
                + "            ]\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"create\",\n"
                + "            \"base\": \"\",\n"
                + "            \"fields\": [\n"
                + "                {\n"
                + "                    \"name\": \"owner\",\n"
                + "                    \"type\": \"name\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"guid\",\n"
                + "                    \"type\": \"uint64\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"workspaceName\",\n"
                + "                    \"type\": \"string\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"workspaceDescription\",\n"
                + "                    \"type\": \"string\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"key\",\n"
                + "                    \"type\": \"string\"\n"
                + "                }\n"
                + "            ]\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"decline\",\n"
                + "            \"base\": \"\",\n"
                + "            \"fields\": [\n"
                + "                {\n"
                + "                    \"name\": \"invitee\",\n"
                + "                    \"type\": \"name\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"guid\",\n"
                + "                    \"type\": \"uint64\"\n"
                + "                }\n"
                + "            ]\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"destroy\",\n"
                + "            \"base\": \"\",\n"
                + "            \"fields\": [\n"
                + "                {\n"
                + "                    \"name\": \"guid\",\n"
                + "                    \"type\": \"uint64\"\n"
                + "                }\n"
                + "            ]\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"file\",\n"
                + "            \"base\": \"\",\n"
                + "            \"fields\": [\n"
                + "                {\n"
                + "                    \"name\": \"id\",\n"
                + "                    \"type\": \"uint64\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"fileID\",\n"
                + "                    \"type\": \"uint128\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"parentID\",\n"
                + "                    \"type\": \"uint128\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"versionID\",\n"
                + "                    \"type\": \"uint128\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"parentVersions\",\n"
                + "                    \"type\": \"uint128[]\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"uploader\",\n"
                + "                    \"type\": \"name\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"lockOwner\",\n"
                + "                    \"type\": \"name\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"timestamp\",\n"
                + "                    \"type\": \"uint64\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"status\",\n"
                + "                    \"type\": \"uint8\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"metadata\",\n"
                + "                    \"type\": \"string\"\n"
                + "                }\n"
                + "            ]\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"fileReceipt\",\n"
                + "            \"base\": \"\",\n"
                + "            \"fields\": [\n"
                + "                {\n"
                + "                    \"name\": \"id\",\n"
                + "                    \"type\": \"uint64\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"fileID\",\n"
                + "                    \"type\": \"uint128\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"versionID\",\n"
                + "                    \"type\": \"uint128\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"user\",\n"
                + "                    \"type\": \"name\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"timestamp\",\n"
                + "                    \"type\": \"uint64\"\n"
                + "                }\n"
                + "            ]\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"fileTag\",\n"
                + "            \"base\": \"\",\n"
                + "            \"fields\": [\n"
                + "                {\n"
                + "                    \"name\": \"id\",\n"
                + "                    \"type\": \"uint64\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"fileID\",\n"
                + "                    \"type\": \"uint128\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"versionID\",\n"
                + "                    \"type\": \"uint128\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"scope\",\n"
                + "                    \"type\": \"uint64\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"value\",\n"
                + "                    \"type\": \"string\"\n"
                + "                }\n"
                + "            ]\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"invite\",\n"
                + "            \"base\": \"\",\n"
                + "            \"fields\": [\n"
                + "                {\n"
                + "                    \"name\": \"inviter\",\n"
                + "                    \"type\": \"name\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"invitee\",\n"
                + "                    \"type\": \"name\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"guid\",\n"
                + "                    \"type\": \"uint64\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"key\",\n"
                + "                    \"type\": \"string\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"permissions\",\n"
                + "                    \"type\": \"userPermission[]\"\n"
                + "                }\n"
                + "            ]\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"lock\",\n"
                + "            \"base\": \"\",\n"
                + "            \"fields\": [\n"
                + "                {\n"
                + "                    \"name\": \"id\",\n"
                + "                    \"type\": \"uint64\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"guid\",\n"
                + "                    \"type\": \"uint128\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"lockOwner\",\n"
                + "                    \"type\": \"name\"\n"
                + "                }\n"
                + "            ]\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"lockfile\",\n"
                + "            \"base\": \"\",\n"
                + "            \"fields\": [\n"
                + "                {\n"
                + "                    \"name\": \"user\",\n"
                + "                    \"type\": \"name\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"guid\",\n"
                + "                    \"type\": \"uint64\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"fileID\",\n"
                + "                    \"type\": \"uint128\"\n"
                + "                }\n"
                + "            ]\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"lockmember\",\n"
                + "            \"base\": \"\",\n"
                + "            \"fields\": [\n"
                + "                {\n"
                + "                    \"name\": \"locker\",\n"
                + "                    \"type\": \"name\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"lockee\",\n"
                + "                    \"type\": \"name\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"guid\",\n"
                + "                    \"type\": \"uint64\"\n"
                + "                }\n"
                + "            ]\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"lockver\",\n"
                + "            \"base\": \"\",\n"
                + "            \"fields\": [\n"
                + "                {\n"
                + "                    \"name\": \"user\",\n"
                + "                    \"type\": \"name\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"guid\",\n"
                + "                    \"type\": \"uint64\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"fileID\",\n"
                + "                    \"type\": \"uint128\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"versionID\",\n"
                + "                    \"type\": \"uint128\"\n"
                + "                }\n"
                + "            ]\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"membership\",\n"
                + "            \"base\": \"\",\n"
                + "            \"fields\": [\n"
                + "                {\n"
                + "                    \"name\": \"id\",\n"
                + "                    \"type\": \"uint64\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"inviter\",\n"
                + "                    \"type\": \"name\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"user\",\n"
                + "                    \"type\": \"name\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"status\",\n"
                + "                    \"type\": \"uint8\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"key\",\n"
                + "                    \"type\": \"string\"\n"
                + "                }\n"
                + "            ]\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"message\",\n"
                + "            \"base\": \"\",\n"
                + "            \"fields\": [\n"
                + "                {\n"
                + "                    \"name\": \"id\",\n"
                + "                    \"type\": \"uint64\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"msgID\",\n"
                + "                    \"type\": \"uint128\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"author\",\n"
                + "                    \"type\": \"name\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"text\",\n"
                + "                    \"type\": \"string\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"timestamp\",\n"
                + "                    \"type\": \"uint64\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"mimeType\",\n"
                + "                    \"type\": \"string\"\n"
                + "                }\n"
                + "            ]\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"messageReceipt\",\n"
                + "            \"base\": \"\",\n"
                + "            \"fields\": [\n"
                + "                {\n"
                + "                    \"name\": \"id\",\n"
                + "                    \"type\": \"uint64\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"msgID\",\n"
                + "                    \"type\": \"uint128\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"user\",\n"
                + "                    \"type\": \"name\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"timestamp\",\n"
                + "                    \"type\": \"uint64\"\n"
                + "                }\n"
                + "            ]\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"offerowner\",\n"
                + "            \"base\": \"\",\n"
                + "            \"fields\": [\n"
                + "                {\n"
                + "                    \"name\": \"guid\",\n"
                + "                    \"type\": \"uint64\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"newowner\",\n"
                + "                    \"type\": \"name\"\n"
                + "                }\n"
                + "            ]\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"permission\",\n"
                + "            \"base\": \"\",\n"
                + "            \"fields\": [\n"
                + "                {\n"
                + "                    \"name\": \"id\",\n"
                + "                    \"type\": \"uint64\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"permissionType\",\n"
                + "                    \"type\": \"name\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"user\",\n"
                + "                    \"type\": \"name\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"scope\",\n"
                + "                    \"type\": \"string\"\n"
                + "                }\n"
                + "            ]\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"remove\",\n"
                + "            \"base\": \"\",\n"
                + "            \"fields\": [\n"
                + "                {\n"
                + "                    \"name\": \"remover\",\n"
                + "                    \"type\": \"name\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"member\",\n"
                + "                    \"type\": \"name\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"guid\",\n"
                + "                    \"type\": \"uint64\"\n"
                + "                }\n"
                + "            ]\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"removefile\",\n"
                + "            \"base\": \"\",\n"
                + "            \"fields\": [\n"
                + "                {\n"
                + "                    \"name\": \"remover\",\n"
                + "                    \"type\": \"name\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"guid\",\n"
                + "                    \"type\": \"uint64\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"fileID\",\n"
                + "                    \"type\": \"uint128\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"versionID\",\n"
                + "                    \"type\": \"uint128\"\n"
                + "                }\n"
                + "            ]\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"removeperm\",\n"
                + "            \"base\": \"\",\n"
                + "            \"fields\": [\n"
                + "                {\n"
                + "                    \"name\": \"user\",\n"
                + "                    \"type\": \"name\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"target\",\n"
                + "                    \"type\": \"name\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"guid\",\n"
                + "                    \"type\": \"uint64\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"permName\",\n"
                + "                    \"type\": \"string\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"scope\",\n"
                + "                    \"type\": \"string\"\n"
                + "                }\n"
                + "            ]\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"removeperms\",\n"
                + "            \"base\": \"\",\n"
                + "            \"fields\": [\n"
                + "                {\n"
                + "                    \"name\": \"user\",\n"
                + "                    \"type\": \"name\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"target\",\n"
                + "                    \"type\": \"name\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"guid\",\n"
                + "                    \"type\": \"uint64\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"permissions\",\n"
                + "                    \"type\": \"userPermission[]\"\n"
                + "                }\n"
                + "            ]\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"removetag\",\n"
                + "            \"base\": \"\",\n"
                + "            \"fields\": [\n"
                + "                {\n"
                + "                    \"name\": \"user\",\n"
                + "                    \"type\": \"name\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"guid\",\n"
                + "                    \"type\": \"uint64\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"fileID\",\n"
                + "                    \"type\": \"uint128\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"versionID\",\n"
                + "                    \"type\": \"uint128\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"isPublic\",\n"
                + "                    \"type\": \"boolean\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"value\",\n"
                + "                    \"type\": \"string\"\n"
                + "                }\n"
                + "            ]\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"rescindowner\",\n"
                + "            \"base\": \"\",\n"
                + "            \"fields\": [\n"
                + "                {\n"
                + "                    \"name\": \"guid\",\n"
                + "                    \"type\": \"uint64\"\n"
                + "                }\n"
                + "            ]\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"unlockfile\",\n"
                + "            \"base\": \"\",\n"
                + "            \"fields\": [\n"
                + "                {\n"
                + "                    \"name\": \"user\",\n"
                + "                    \"type\": \"name\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"guid\",\n"
                + "                    \"type\": \"uint64\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"fileID\",\n"
                + "                    \"type\": \"uint128\"\n"
                + "                }\n"
                + "            ]\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"unlockmember\",\n"
                + "            \"base\": \"\",\n"
                + "            \"fields\": [\n"
                + "                {\n"
                + "                    \"name\": \"locker\",\n"
                + "                    \"type\": \"name\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"lockee\",\n"
                + "                    \"type\": \"name\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"guid\",\n"
                + "                    \"type\": \"uint64\"\n"
                + "                }\n"
                + "            ]\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"unlockver\",\n"
                + "            \"base\": \"\",\n"
                + "            \"fields\": [\n"
                + "                {\n"
                + "                    \"name\": \"user\",\n"
                + "                    \"type\": \"name\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"guid\",\n"
                + "                    \"type\": \"uint64\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"fileID\",\n"
                + "                    \"type\": \"uint128\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"versionID\",\n"
                + "                    \"type\": \"uint128\"\n"
                + "                }\n"
                + "            ]\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"update\",\n"
                + "            \"base\": \"\",\n"
                + "            \"fields\": [\n"
                + "                {\n"
                + "                    \"name\": \"user\",\n"
                + "                    \"type\": \"name\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"guid\",\n"
                + "                    \"type\": \"uint64\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"workspaceDescription\",\n"
                + "                    \"type\": \"string\"\n"
                + "                }\n"
                + "            ]\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"userPermission\",\n"
                + "            \"base\": \"\",\n"
                + "            \"fields\": [\n"
                + "                {\n"
                + "                    \"name\": \"permName\",\n"
                + "                    \"type\": \"string\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"scope\",\n"
                + "                    \"type\": \"string\"\n"
                + "                }\n"
                + "            ]\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"workspace\",\n"
                + "            \"base\": \"\",\n"
                + "            \"fields\": [\n"
                + "                {\n"
                + "                    \"name\": \"id\",\n"
                + "                    \"type\": \"uint64\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"name\",\n"
                + "                    \"type\": \"string\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"description\",\n"
                + "                    \"type\": \"string\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"owner\",\n"
                + "                    \"type\": \"name\"\n"
                + "                },\n"
                + "                {\n"
                + "                    \"name\": \"newowner\",\n"
                + "                    \"type\": \"name\"\n"
                + "                }\n"
                + "            ]\n"
                + "        }\n"
                + "    ],\n"
                + "    \"types\": [\n"
                + "        {\n"
                + "            \"new_type_name\": \"boolean\",\n"
                + "            \"type\": \"uint8\"\n"
                + "        }\n"
                + "    ],\n"
                + "    \"actions\": [\n"
                + "        {\n"
                + "            \"name\": \"accept\",\n"
                + "            \"type\": \"accept\",\n"
                + "            \"ricardian_contract\": \"\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"acceptowner\",\n"
                + "            \"type\": \"acceptowner\",\n"
                + "            \"ricardian_contract\": \"\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"ackfile\",\n"
                + "            \"type\": \"ackfile\",\n"
                + "            \"ricardian_contract\": \"\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"ackmessage\",\n"
                + "            \"type\": \"ackmessage\",\n"
                + "            \"ricardian_contract\": \"\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"addfile\",\n"
                + "            \"type\": \"addfile\",\n"
                + "            \"ricardian_contract\": \"\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"addmessage\",\n"
                + "            \"type\": \"addmessage\",\n"
                + "            \"ricardian_contract\": \"\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"addperm\",\n"
                + "            \"type\": \"addperm\",\n"
                + "            \"ricardian_contract\": \"\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"addperms\",\n"
                + "            \"type\": \"addperms\",\n"
                + "            \"ricardian_contract\": \"\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"addtag\",\n"
                + "            \"type\": \"addtag\",\n"
                + "            \"ricardian_contract\": \"\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"create\",\n"
                + "            \"type\": \"create\",\n"
                + "            \"ricardian_contract\": \"\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"decline\",\n"
                + "            \"type\": \"decline\",\n"
                + "            \"ricardian_contract\": \"\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"destroy\",\n"
                + "            \"type\": \"destroy\",\n"
                + "            \"ricardian_contract\": \"\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"invite\",\n"
                + "            \"type\": \"invite\",\n"
                + "            \"ricardian_contract\": \"\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"lockfile\",\n"
                + "            \"type\": \"lockfile\",\n"
                + "            \"ricardian_contract\": \"\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"lockmember\",\n"
                + "            \"type\": \"lockmember\",\n"
                + "            \"ricardian_contract\": \"\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"lockver\",\n"
                + "            \"type\": \"lockver\",\n"
                + "            \"ricardian_contract\": \"\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"offerowner\",\n"
                + "            \"type\": \"offerowner\",\n"
                + "            \"ricardian_contract\": \"\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"remove\",\n"
                + "            \"type\": \"remove\",\n"
                + "            \"ricardian_contract\": \"\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"removefile\",\n"
                + "            \"type\": \"removefile\",\n"
                + "            \"ricardian_contract\": \"\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"removeperm\",\n"
                + "            \"type\": \"removeperm\",\n"
                + "            \"ricardian_contract\": \"\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"removeperms\",\n"
                + "            \"type\": \"removeperms\",\n"
                + "            \"ricardian_contract\": \"\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"removetag\",\n"
                + "            \"type\": \"removetag\",\n"
                + "            \"ricardian_contract\": \"\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"rescindowner\",\n"
                + "            \"type\": \"rescindowner\",\n"
                + "            \"ricardian_contract\": \"\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"unlockfile\",\n"
                + "            \"type\": \"unlockfile\",\n"
                + "            \"ricardian_contract\": \"\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"unlockmember\",\n"
                + "            \"type\": \"unlockmember\",\n"
                + "            \"ricardian_contract\": \"\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"unlockver\",\n"
                + "            \"type\": \"unlockver\",\n"
                + "            \"ricardian_contract\": \"\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"update\",\n"
                + "            \"type\": \"update\",\n"
                + "            \"ricardian_contract\": \"\"\n"
                + "        }\n"
                + "    ],\n"
                + "    \"tables\": [\n"
                + "        {\n"
                + "            \"name\": \"filereceipts\",\n"
                + "            \"type\": \"fileReceipt\",\n"
                + "            \"index_type\": \"i64\",\n"
                + "            \"key_names\": [],\n"
                + "            \"key_types\": []\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"files\",\n"
                + "            \"type\": \"file\",\n"
                + "            \"index_type\": \"i64\",\n"
                + "            \"key_names\": [],\n"
                + "            \"key_types\": []\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"filetags\",\n"
                + "            \"type\": \"fileTag\",\n"
                + "            \"index_type\": \"i64\",\n"
                + "            \"key_names\": [],\n"
                + "            \"key_types\": []\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"locks\",\n"
                + "            \"type\": \"lock\",\n"
                + "            \"index_type\": \"i64\",\n"
                + "            \"key_names\": [],\n"
                + "            \"key_types\": []\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"membership\",\n"
                + "            \"type\": \"membership\",\n"
                + "            \"index_type\": \"i64\",\n"
                + "            \"key_names\": [],\n"
                + "            \"key_types\": []\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"messages\",\n"
                + "            \"type\": \"message\",\n"
                + "            \"index_type\": \"i64\",\n"
                + "            \"key_names\": [],\n"
                + "            \"key_types\": []\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"msgreceipts\",\n"
                + "            \"type\": \"messageReceipt\",\n"
                + "            \"index_type\": \"i64\",\n"
                + "            \"key_names\": [],\n"
                + "            \"key_types\": []\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"permissions\",\n"
                + "            \"type\": \"permission\",\n"
                + "            \"index_type\": \"i64\",\n"
                + "            \"key_names\": [],\n"
                + "            \"key_types\": []\n"
                + "        },\n"
                + "        {\n"
                + "            \"name\": \"workspace\",\n"
                + "            \"type\": \"workspace\",\n"
                + "            \"index_type\": \"i64\",\n"
                + "            \"key_names\": [],\n"
                + "            \"key_types\": []\n"
                + "        }\n"
                + "    ],\n"
                + "    \"ricardian_clauses\": [],\n"
                + "    \"abi_extensions\": []\n"
                + "}";
        Transaction t = chain.setContract("inita", new ByteArrayInputStream(abi.getBytes()), new ByteArrayInputStream("foobar".getBytes()));
        System.out.println(t.toString());
    }

}
